POST http://localhost:8080/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "password"
}

###

POST http://localhost:8080/user/signup HTTP/1.1
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "password"
}

###
POST http://localhost:8080/student/add HTTP/1.1
Content-Type: multipart/form-data

{
    "name": "student",
    "email": "student@gmail.com",
    "gender": "male",
    "address": "address",
    "phone": "1234567890",
    "degree": "B.Tech",
    "degreeStatus": "graduate",
    "year": "1",
    "collegeName": "college"
}

###
GET http://localhost:8080/student/get HTTP/1.1

###
GET http://localhost:8080/student/get/661440eea740936c9b1c6599 HTTP/1.1

###
DELETE http://localhost:8080/student/delete/661459e3396c256884a4c743 HTTP/1.1
